# Generated by Django 4.1.7 on 2023-02-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Author', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tag', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebNovels',
            fields=[
                ('name', models.CharField(default='Webnovel', max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('views', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('length', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('On a Break', 'On a Break'), ('Ongoing', 'Ongoing')], max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebNovels.author')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebNovels.tag')),
            ],
        ),
    ]
