# Generated by Django 4.1.7 on 2023-03-10 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebNovels', '0002_remove_webnovels_tags_webnovels_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='webnovels',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
