# Generated by Django 3.2.12 on 2023-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebNovels', '0005_alter_webnovels_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webnovels',
            name='tags',
            field=models.ManyToManyField(blank=True, default='Tag', to='WebNovels.Tag'),
        ),
    ]
